#!/bin/tcsh -f

# Number of days
set dys = 22371  # number of dates

set som = ('7x5' '8x6')
set x = ('7' '8')
set y = ('5' '6')
set len = ('32168' '32168') #the vector length

set input_dir = /data3/duvivier/SOM/training/rmse
set som_dir = /data3/duvivier/SOM/training/rmse
set visual_dir = /data3/duvivier/SOM/training/rmse

set s = 1 # SOM size
while ($s <= 2) 

      ln -s $input_dir/wrf10_wrf50_erai_wind.dat SOM_input_data.txt
      ln -s $som_dir/{$som[$s]}/winds0.01_rlen1000000_r4.cod SOM_output_data.txt
      ln -s $visual_dir/{$som[$s]}/wrf10_wrf50_erai_winds0.01_rlen1000000_r4.vis visual.txt 

      sed -e "s/my_len/"{$len[$s]}"/" \
          -e "s/my_dys/"{$dys}"/" \
          -e "s/my_x/"{$x[$s]}"/" \
          -e "s/my_y/"{$y[$s]}"/" calc_som_fit.f90 > final_prog.f90

      pgf90 final_prog.f90
      a.out

      mv rmse.txt {$som[$s]}.rmse.txt
      mv bias.txt {$som[$s]}.bias.txt
      mv corr.txt {$som[$s]}.corr.txt
      mv mse.txt {$som[$s]}}.mse.txt
      mv mae.txt {$som[$s]}}.mae.txt

      rm final_prog.f90
      rm SOM_input_data.txt
      rm SOM_output_data.txt
      rm visual.txt

   @ s ++
end
